import { call, ok, done, save, claims } from './lib.mjs';
const stamp = Date.now();
const PASS = 'tenant-pass-123';
const ownerEmail = `org-owner${stamp}@example.com`;
let r = await call('POST', '/tenant/api/auth/register', { name: 'Olivia Owner', email: ownerEmail, password: PASS, organization: 'Globex' });
const owner = r.body.token;
ok('owner registered', r.status === 200);
r = await call('GET', '/tenant/api/org', null, owner);
ok('org overview + counts', r.status === 200 && r.body?.name === 'Globex' && r.body?.counts?.members === 1, JSON.stringify(r.body?.counts));
r = await call('PUT', '/tenant/api/org', { name: 'Globex Corp', onboarding: { industry: 'software', goals: ['api'] } }, owner);
ok('update org', r.status === 200 && r.body?.name === 'Globex Corp' && r.body?.onboarding?.industry === 'software', r.status);
r = await call('GET', '/tenant/api/org/roles', null, owner);
ok('three system roles', r.status === 200 && r.body?.doc?.length === 3, r.body?.doc?.map(x => x.name).join(','));
const roles = Object.fromEntries(r.body.doc.map(x => [x.system, x._id]));
r = await call('POST', '/tenant/api/org/roles', { name: 'Editor', permissions: ['records:view', 'records:edit', 'build'] }, owner);
ok('custom role', r.status === 200 && r.body?.name === 'Editor', r.body?.message);
const editorRole = r.body._id;
r = await call('POST', '/tenant/api/org/roles', { name: 'Old style', permissions: ['data:*', 'view-invoices', 'build'] }, owner);
ok('old keys normalized (WO-21)', r.status === 200 && JSON.stringify(r.body?.permissions) === JSON.stringify(['records:view', 'records:create', 'records:edit', 'records:delete', 'build']), JSON.stringify(r.body?.permissions));
await call('DELETE', `/tenant/api/org/roles/${r.body?._id}`, null, owner);
r = await call('POST', '/tenant/api/org/roles', { name: 'Bad', permissions: ['rm -rf'] }, owner);
ok('unknown permission refused', r.status === 400, r.body?.message);
r = await call('POST', '/tenant/api/org/invitations', { email: 'not-an-email', role: roles.member }, owner);
ok('bad email refused', r.status === 400);
r = await call('POST', '/tenant/api/org/invitations', { email: `new-member${stamp}@example.com`, name: 'Nina New', role: roles.member }, owner);
ok('invite a new person', r.status === 200 && r.body?.role?.name === 'Member', r.body?.message);
r = await call('POST', '/tenant/api/org/invitations', { email: `editor${stamp}@example.com`, role: editorRole }, owner);
ok('invite with custom role', r.status === 200);
r = await call('POST', '/tenant/api/org/invitations', { email: `x${stamp}@example.com`, role: roles.owner }, owner);
ok('owner role cannot be invited', r.status === 400, r.body?.message);
r = await call('GET', '/tenant/api/org/invitations', null, owner);
ok('pending invitations listed', r.status === 200 && r.body?.doc?.length === 2 && !JSON.stringify(r.body).includes('tokenHash'), r.body?.doc?.length);
// A second person with their own org, to accept with an existing account
const otherEmail = `existing${stamp}@example.com`;
r = await call('POST', '/tenant/api/auth/register', { name: 'Eve Existing', email: otherEmail, password: PASS, organization: 'Eve Co' });
const eve = r.body.token;
r = await call('POST', '/tenant/api/org/invitations', { email: otherEmail, role: roles.admin }, owner);
ok('invite an existing account', r.status === 200);
save({ stamp, PASS, owner, eve, ownerEmail, otherEmail, roles, editorRole });
done();
