import { call, ok, done, load, claims } from './lib.mjs';
const s = load();
const [nina, editor, existing] = process.argv.slice(2);
let r = await call('GET', `/tenant/api/invitations/${nina}`);
ok('invitation info (new person)', r.status === 200 && r.body?.organization?.name === 'Globex Corp' && r.body?.existingAccount === false && r.body?.role === 'Member', JSON.stringify(r.body));
r = await call('POST', `/tenant/api/invitations/${nina}/accept`, { name: 'Nina New', password: 'short' });
ok('short password refused', r.status === 400);
r = await call('POST', `/tenant/api/invitations/${nina}/accept`, { name: 'Nina New', password: 'nina-pass-123' });
ok('new person accepts → token in Globex', r.status === 200 && r.body?.token, r.body?.message);
const ninaT = r.body.token;
r = await call('POST', `/tenant/api/invitations/${nina}/accept`, { name: 'Nina New', password: 'nina-pass-123' });
ok('link works once', r.status === 400 && r.body?.code === 'invitation_invalid');
r = await call('GET', '/tenant/api/auth/self', null, ninaT);
ok('Nina is a Member of Globex', r.body?.organization?.name === 'Globex Corp' && r.body?.role?.system === 'member', r.body?.role?.name);
r = await call('GET', `/tenant/api/invitations/${existing}`);
ok('invitation info knows the account exists', r.body?.existingAccount === true);
r = await call('POST', `/tenant/api/invitations/${existing}/accept`, { password: 'wrong' });
ok('existing account needs its password', r.status === 400 && r.body?.code === 'wrong_password');
r = await call('POST', `/tenant/api/invitations/${existing}/accept`, { password: s.PASS });
ok('existing account accepts', r.status === 200 && r.body?.token);
let eveT = r.body.token;
r = await call('GET', '/tenant/api/org/list', null, eveT);
ok('Eve belongs to two organizations', r.body?.doc?.length === 2, r.body?.doc?.map(o => o.name).join(', '));
const eveCo = r.body.doc.find(o => o.name === 'Eve Co');
r = await call('POST', `/tenant/api/org/switch/${eveCo._id}`, null, eveT);
ok('switch organization → new token', r.status === 200 && claims(r.body.token).org === eveCo._id);
const eveOld = eveT; eveT = r.body.token;
r = await call('GET', '/tenant/api/auth/self', null, eveOld);
ok('the token she switched from is signed out', r.status === 401);
r = await call('GET', '/tenant/api/org', null, eveT);
ok('now working in Eve Co', r.body?.name === 'Eve Co');
r = await call('POST', `/tenant/api/org/switch/000000000000000000000000`, null, eveT);
ok("can't switch into an org you're not in", r.status === 404);
// Editor accepts
r = await call('POST', `/tenant/api/invitations/${editor}/accept`, { name: 'Ed Editor', password: 'ed-pass-12345' });
const edT = r.body.token;
ok('editor accepts', r.status === 200);
// Permissions
r = await call('POST', '/tenant/api/org/invitations', { email: `z${s.stamp}@example.com`, role: s.roles.member }, ninaT);
ok('a Member cannot invite', r.status === 403, r.status);
r = await call('PUT', '/tenant/api/org', { name: 'Hacked' }, ninaT);
ok('a Member cannot edit the org', r.status === 403);
r = await call('GET', '/tenant/api/org/members', null, s.owner);
ok('four members', r.body?.total === 4, r.body?.total);
const members = Object.fromEntries(r.body.doc.map(m => [m.user.name, m._id]));
r = await call('PUT', `/tenant/api/org/members/${members['Nina New']}`, { role: s.editorRole }, s.owner);
ok("change Nina's role", r.status === 200 && r.body?.role?.name === 'Editor');
r = await call('PUT', `/tenant/api/org/members/${members['Olivia Owner']}`, { role: s.roles.member }, s.owner);
ok("owner's role can't change", r.status === 400);
r = await call('DELETE', `/tenant/api/org/roles/${s.editorRole}`, null, s.owner);
ok('role in use cannot be deleted', r.status === 400, r.body?.message);
r = await call('DELETE', `/tenant/api/org/members/${members['Ed Editor']}`, null, s.owner);
ok('remove a member', r.status === 200);
r = await call('GET', '/tenant/api/org', null, edT);
ok("removed member's token stops working", r.status === 401 && r.body?.code === 'ORG_ACCESS_REVOKED', `${r.status} ${r.body?.code}`);
r = await call('GET', '/tenant/api/auth/self', null, edT);
ok('…but they can still reach their account', r.status === 401 || r.status === 200, r.status);
r = await call('DELETE', '/tenant/api/org/members/me', null, ninaT);
ok('a member can leave', r.status === 200);
r = await call('DELETE', `/tenant/api/org/members/${members['Olivia Owner']}`, null, s.owner);
ok("the owner can't leave", r.status === 400);
r = await call('POST', '/tenant/api/org/transfer-ownership', { member: members['Eve Existing'] }, s.owner);
ok('transfer ownership', r.status === 200, r.body?.message);
r = await call('GET', '/tenant/api/auth/self', null, s.owner);
ok('previous owner is now Admin', r.body?.role?.system === 'admin', r.body?.role?.name);
r = await call('POST', '/tenant/api/org/transfer-ownership', { member: members['Olivia Owner'] }, s.owner);
ok('only the owner can transfer', r.status === 403);
done();
