import { call, ok, done, save } from './lib.mjs';
const stamp = Date.now();
const PASS = 'tenant-pass-123';
let r = await call('POST', '/tenant/api/auth/register', { name: 'Pat Projects', email: `pat${stamp}@example.com`, password: PASS, organization: 'Initech' , country: 'BD'});
const pat = r.body.token;
r = await call('POST', '/tenant/api/auth/register', { name: 'Other', email: `other${stamp}@example.com`, password: PASS, organization: 'Umbrella' , country: 'BD'});
const other = r.body.token;
r = await call('POST', '/tenant/api/projects', { name: 'CRM', type: 'app', description: 'Clients and deals' }, pat);
ok('create app project', r.status === 200 && r.body?.slug === 'crm' && /^initech(-\d+)?-crm$/.test(r.body?.publicSlug), JSON.stringify({ slug: r.body?.slug, pub: r.body?.publicSlug, m: r.body?.message }));
const crm = r.body._id;
r = await call('POST', '/tenant/api/projects', { name: 'CRM', type: 'app' }, pat);
ok('same name gets a new slug', r.status === 200 && r.body?.slug === 'crm-2', r.body?.slug);
const crm2 = r.body._id;
r = await call('POST', '/tenant/api/projects', { name: 'Marketing site', type: 'website', domains: ['initech.example.com'] }, pat);
ok('create website project', r.status === 200 && r.body?.type === 'website' && r.body?.domains?.[0] === 'initech.example.com', r.body?.message);
const site = r.body._id;
r = await call('POST', '/tenant/api/projects', { name: 'Bad', domains: ['not a domain'] }, pat);
ok('bad domain refused', r.status === 400, r.body?.message);
r = await call('POST', '/tenant/api/projects', { name: 'Bad', type: 'spaceship' }, pat);
ok('bad type refused', r.status === 400);
r = await call('GET', '/tenant/api/projects', null, pat);
ok('list: three projects with model counts (the website has its kit: pages, SEO, contents, site design)', r.status === 200 && r.body?.doc?.length === 3 && r.body.doc.every(p => p.models === (p.type === 'website' ? 4 : 0)), JSON.stringify(r.body?.doc?.map(p => p.models)));
r = await call('GET', '/tenant/api/auth/self', null, pat);
ok('self lists the projects', r.body?.projects?.length === 3);
r = await call('GET', `/tenant/api/projects/${crm}`, null, other);
ok("another org's project is 404", r.status === 404);
r = await call('PUT', `/tenant/api/projects/${crm}`, { name: 'Hijack' }, other);
ok("another org can't edit it", r.status === 404);
r = await call('GET', '/tenant/api/projects', null, other);
ok('other org sees none', r.body?.doc?.length === 0);
r = await call('PUT', `/tenant/api/projects/${crm2}`, { name: 'CRM (old)', isActive: false }, pat);
ok('archive a project', r.status === 200 && r.body?.isActive === false);
r = await call('GET', '/tenant/api/projects', null, pat);
ok('archived hidden from the list', r.body?.doc?.length === 2);
r = await call('GET', '/tenant/api/projects?archived=1', null, pat);
ok('…and shown with ?archived=1', r.body?.doc?.length === 3);
r = await call('DELETE', `/tenant/api/projects/${crm2}`, null, pat);
ok('delete an empty project', r.status === 200);
save({ pat, other, crm, site, stamp });
done();
