const B2CPaymentUsingPost = {"body":{"type":"object","required":["amount","currency","merchantInvoiceNumber","receiverMSISDN"],"properties":{"amount":{"type":"string","description":"Amount"},"currency":{"type":"string","description":"Currency(BDT)"},"merchantInvoiceNumber":{"type":"string","description":"Merchant Invoice Number"},"receiverMSISDN":{"type":"string","description":"Receiver MSISDN"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"completedTime":{"type":"string"},"trxID":{"type":"string"},"transactionStatus":{"type":"string"},"amount":{"type":"string"},"currency":{"type":"string"},"merchantInvoiceNumber":{"type":"string"},"receiverMSISDN":{"type":"string"},"b2cFee":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CapturePaymentUsingPost = {"metadata":{"allOf":[{"type":"object","properties":{"paymentID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["paymentID"]},{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"paymentID":{"type":"string"},"createTime":{"type":"string"},"updateTime":{"type":"string"},"trxID":{"type":"string"},"transactionStatus":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CreatePaymentUsingPost = {"body":{"type":"object","required":["amount","currency","intent","merchantInvoiceNumber"],"properties":{"amount":{"type":"string","description":"Amount"},"currency":{"type":"string","description":"Currency(BDT)"},"intent":{"type":"string","description":"Intent(sale/authorization)"},"merchantInvoiceNumber":{"type":"string","description":"Merchant Invoice Number"},"merchantAssociationInfo":{"type":"string","description":"Merchant Association Info"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"paymentID":{"type":"string"},"createTime":{"type":"string"},"orgLogo":{"type":"string"},"orgName":{"type":"string"},"transactionStatus":{"type":"string"},"amount":{"type":"string"},"currency":{"type":"string"},"intent":{"type":"string"},"merchantInvoiceNumber":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ExecutePaymentUsingPost = {"metadata":{"allOf":[{"type":"object","properties":{"paymentID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["paymentID"]},{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"paymentID":{"type":"string"},"createTime":{"type":"string"},"updateTime":{"type":"string"},"trxID":{"type":"string"},"transactionStatus":{"type":"string"},"amount":{"type":"string"},"currency":{"type":"string"},"intent":{"type":"string"},"merchantInvoiceNumber":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetTokenUsingPost = {"body":{"type":"object","required":["app_key","app_secret"],"properties":{"app_key":{"type":"string","description":"App Key"},"app_secret":{"type":"string","description":"App Secret"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"username":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"password":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["username","password"]}]},"response":{"200":{"type":"object","properties":{"expires_in":{"type":"string"},"id_token":{"type":"string"},"refresh_token":{"type":"string"},"token_type":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const IntraAccountTransferUsingPost = {"body":{"type":"object","required":["amount","currency","transferType"],"properties":{"amount":{"type":"string","description":"Amount"},"currency":{"type":"string","description":"Currency(BDT)"},"transferType":{"type":"string","description":"TransferType(Collection2Disbursement/Disbursement2Collection)"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"amount":{"type":"string"},"completedTime":{"type":"string"},"currency":{"type":"string"},"transactionStatus":{"type":"string"},"transferType":{"type":"string"},"trxID":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostCheckoutPaymentRefund = {"body":{"type":"object","required":["paymentId","trxID"],"properties":{"amount":{"type":"string","description":"Amount"},"paymentId":{"type":"string","description":"paymentId"},"trxID":{"type":"string","description":"trxID"},"sku":{"type":"string","description":"sku"},"reason":{"type":"string","description":"reason"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"completedTime":{"type":"string"},"originalTrxID":{"type":"string"},"refundTrxID":{"type":"string"},"transactionStatus":{"type":"string"},"amount":{"type":"string"},"currency":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const QueryOrganizationBalanceUsingGet = {"metadata":{"allOf":[{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"organizationBalance":{"type":"array","items":{"type":"object","properties":{"accountHolderName":{"type":"string"},"accountStatus":{"type":"string"},"accountTypeName":{"type":"string"},"availableBalance":{"type":"string"},"currency":{"type":"string"},"currentBalance":{"type":"string"},"updateTime":{"type":"string"}}}}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const QueryPaymentUsingGet = {"metadata":{"allOf":[{"type":"object","properties":{"paymentID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["paymentID"]},{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"paymentID":{"type":"string"},"createTime":{"type":"string"},"updateTime":{"type":"string"},"trxID":{"type":"string"},"transactionStatus":{"type":"string"},"amount":{"type":"string"},"currency":{"type":"string"},"intent":{"type":"string"},"merchantInvoiceNumber":{"type":"string"},"refundAmount":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const RefreshTokenUsingPost = {"body":{"type":"object","required":["app_key","app_secret","refresh_token"],"properties":{"app_key":{"type":"string","description":"App Key"},"app_secret":{"type":"string","description":"App Secret"},"refresh_token":{"type":"string","description":"Refresh Token"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"username":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"password":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["username","password"]}]},"response":{"200":{"type":"object","properties":{"expires_in":{"type":"string"},"id_token":{"type":"string"},"refresh_token":{"type":"string"},"token_type":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const SearchTransactionUsingGet = {"metadata":{"allOf":[{"type":"object","properties":{"trxID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["trxID"]},{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"amount":{"type":"string"},"completedTime":{"type":"string"},"currency":{"type":"string"},"customerMsisdn":{"type":"string"},"initiationTime":{"type":"string"},"organizationShortCode":{"type":"string"},"transactionReference":{"type":"string"},"transactionStatus":{"type":"string"},"transactionType":{"type":"string"},"trxID":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const VoidPaymentUsingPost = {"metadata":{"allOf":[{"type":"object","properties":{"paymentID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["paymentID"]},{"type":"object","properties":{"Authorization":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"X-APP-Key":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["Authorization","X-APP-Key"]}]},"response":{"200":{"type":"object","properties":{"paymentID":{"type":"string"},"createTime":{"type":"string"},"updateTime":{"type":"string"},"trxID":{"type":"string"},"transactionStatus":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
export { B2CPaymentUsingPost, CapturePaymentUsingPost, CreatePaymentUsingPost, ExecutePaymentUsingPost, GetTokenUsingPost, IntraAccountTransferUsingPost, PostCheckoutPaymentRefund, QueryOrganizationBalanceUsingGet, QueryPaymentUsingGet, RefreshTokenUsingPost, SearchTransactionUsingGet, VoidPaymentUsingPost }
