import { SettingsType } from '../../imports.js';

const settings: SettingsType<any> = {
	elementType: {
		title: 'Element type',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {
			sort: true,
			default: true,
		},
	},
	elementName: {
		title: 'Element name',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	elementId: {
		title: 'Element id',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	elementSlug: {
		title: 'Element slug',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	sessionId: {
		title: 'Session id',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	elementText: {
		title: 'Element text',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	elementHref: {
		title: 'Element href',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	elementTag: {
		title: 'Element tag',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	pageSlug: {
		title: 'Page slug',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	pageTitle: {
		title: 'Page title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	ipAddress: {
		title: 'Ip address',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true, default: true },
	},
	userAgent: {
		title: 'User agent',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	locationCity: {
		title: 'City',
		type: 'string',
		search: true,
		sort: true,
		edit: true,
		trim: true,
		filter: {
			name: 'locationCity',
			field: 'locationCity_in',
			type: 'multi-select',
			label: 'City',
			title: 'Filter by City',
			category: 'distinct',
			key: 'locationCity',
		},
		schema: {
			sort: true,
		},
	},
	locationCountry: {
		title: 'Country',
		type: 'string',
		search: true,
		sort: true,
		edit: true,
		trim: true,
		filter: {
			name: 'locationCountry',
			field: 'locationCountry_in',
			type: 'multi-select',
			label: 'Country',
			title: 'Filter by Country',
			category: 'distinct',
			key: 'locationCountry',
		},
		schema: {
			sort: true,
		},
	},
	locationRegion: {
		title: 'Location region',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	deviceType: {
		title: 'Device type',
		type: 'string',
		sort: true,
		search: true,
		edit: true,
		trim: true,
		filter: {
			name: 'deviceType',
			field: 'deviceType_in',
			type: 'multi-select',
			label: 'DeviceType',
			title: 'Filter by DeviceType',
			options: [
				{
					label: 'Desktop',
					value: 'desktop',
				},
				{
					label: 'Mobile',
					value: 'mobile',
				},
				{
					label: 'Tablet',
					value: 'tablet',
				},
				{
					label: 'Other',
					value: 'other',
				},
			],
		},
		schema: {
			type: 'select',
			options: [
				{
					label: 'Desktop',
					value: 'desktop',
				},
				{
					label: 'Mobile',
					value: 'mobile',
				},
				{
					label: 'Tablet',
					value: 'tablet',
				},
				{
					label: 'Other',
					value: 'other',
				},
			],
		},
	},
	deviceBrand: {
		title: 'Device brand',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	deviceModel: {
		title: 'Device model',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	deviceOs: {
		title: 'Device os',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			sort: true,
		},
	},
	deviceBrowser: {
		title: 'Device browser',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: { sort: true },
	},
	locationCountryCode: {
		title: 'Location country code',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			sort: true,
		},
	},
	locationRegionCode: {
		title: 'Location region code',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	locationTimeZone: {
		title: 'Location time zone',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	locationISP: {
		title: 'Location ISP',
		type: 'string',
		sort: true,
		search: false,
		edit: true,

		schema: {},
	},
	referrer: {
		title: 'Referrer',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	customref: {
		title: 'Customref',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			default: true,
			sort: true,
		},
	},
	utmSource: {
		title: 'Utm source',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	clickType: {
		title: 'Click type',
		type: 'string',
		sort: true,
		search: true,
		edit: true,
		trim: true,
		filter: {
			name: 'clickType',
			field: 'clickType_in',
			type: 'multi-select',
			label: 'ClickType',
			title: 'Filter by ClickType',
			options: [
				{
					label: 'Click',
					value: 'click',
				},
				{
					label: 'Hover',
					value: 'hover',
				},
				{
					label: 'Focus',
					value: 'focus',
				},
				{
					label: 'Submit',
					value: 'submit',
				},
				{
					label: 'Other',
					value: 'other',
				},
			],
		},
		schema: {
			type: 'select',
			options: [
				{
					label: 'Click',
					value: 'click',
				},
				{
					label: 'Hover',
					value: 'hover',
				},
				{
					label: 'Focus',
					value: 'focus',
				},
				{
					label: 'Submit',
					value: 'submit',
				},
				{
					label: 'Other',
					value: 'other',
				},
			],
		},
	},
	eventCategory: {
		title: 'Event category',
		type: 'string',
		sort: true,
		search: true,
		edit: true,
		trim: true,
		filter: {
			name: 'eventCategory',
			field: 'eventCategory_in',
			type: 'multi-select',
			label: 'EventCategory',
			title: 'Filter by EventCategory',
			options: [
				{
					label: 'Navigation',
					value: 'navigation',
				},
				{
					label: 'Engagement',
					value: 'engagement',
				},
				{
					label: 'Conversion',
					value: 'conversion',
				},
				{
					label: 'Social',
					value: 'social',
				},
				{
					label: 'Download',
					value: 'download',
				},
				{
					label: 'Other',
					value: 'other',
				},
			],
		},
		schema: {
			type: 'select',
			options: [
				{
					label: 'Navigation',
					value: 'navigation',
				},
				{
					label: 'Engagement',
					value: 'engagement',
				},
				{
					label: 'Conversion',
					value: 'conversion',
				},
				{
					label: 'Social',
					value: 'social',
				},
				{
					label: 'Download',
					value: 'download',
				},
				{
					label: 'Other',
					value: 'other',
				},
			],
		},
	},
	eventName: {
		title: 'Event name',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			sort: true,
			default: true,
		},
	},
	conversionType: {
		title: 'Conversion type',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	isBot: {
		title: 'Is bot',
		type: 'boolean',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'isBot',
			type: 'boolean',
			label: 'Is bot',
			title: 'Filter by Is bot',
		},
		schema: {},
	},
	botName: {
		title: 'Bot name',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	tags: {
		title: 'Tags',
		type: 'array',
		sort: false,
		search: false,
		edit: true,
		schema: {},
	},
	fbclid: {
		title: 'Fbclid',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	createdAt: {
		title: 'Clicked At',
		type: 'date',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'createdAt',
			type: 'date',
			label: 'Created at',
			title: 'Filter by Created at',
		},
		schema: {
			type: 'date',
			sort: true,
		},
	},
};

export default settings;
