import { SettingsType } from '../../imports.js';

const settings: SettingsType<any> = {
	code: {
		title: 'Code',
		type: 'string',
		search: true,
		schema: {
			sort: true,
		},
	},
	icon: { title: 'Icon', type: 'uri', edit: true, schema: { type: 'image' } },
	name: {
		title: 'Name',
		type: 'string',
		search: true,
		edit: true,
		required: true,
		schema: {
			default: true,
			sort: true,
		},
	},
	description: {
		title: 'Description',
		type: 'string',
		edit: true,
		schema: {
			type: 'textarea',
			default: true,
		},
	},
	category: {
		title: 'Category',
		type: 'string',
		sort: true,
		search: true,
		edit: true,
		required: true,
		trim: true,
		filter: {
			name: 'category',
			field: 'category_in',
			type: 'multi-select',
			label: 'Category',
			title: 'Filter by Category',
			category: 'distinct',
			key: 'category',
		},
		schema: {
			sort: true,
			default: true,
		},
	},
	url: {
		title: 'URL',
		type: 'uri',
		edit: true,
		search: true,
		trim: true,
		schema: {
			default: true,
			type: 'string',
			tableType: 'external-link',
			viewType: 'external-link',
			copy: true,
			tooltip: 'Resource Link, open in a new tab',
			helperText:
				'Enter the URL of the resource, can be the link of internal document or external website',
		},
	},
	type: {
		title: 'Resource Type',
		type: 'string',
		sort: true,
		search: true,
		edit: true,
		filter: {
			name: 'type',
			field: 'type_in',
			type: 'multi-select',
			label: 'Type',
			title: 'Filter by Type',
			options: [
				{ label: 'Website', value: 'website' },
				{ label: 'Artice', value: 'artice' },
				{ label: 'Documentation', value: 'documentation' },
				{ label: 'Inspiration', value: 'inspiration' },
				{ label: 'Resource', value: 'resource' },
				{ label: 'Tutorial', value: 'tutorial' },
				{ label: 'Video', value: 'video' },
				{ label: 'Git Repo', value: 'git-repo' },
				{ label: 'Internal Doc', value: 'internal-doc' },
				{ label: 'Mockup', value: 'mockup' },
				{ label: 'Audio', value: 'audio' },
				{ label: 'Podcast', value: 'podcast' },
				{ label: 'Blog', value: 'blog' },
				{ label: 'Book', value: 'book' },
				{ label: 'Other', value: 'other' },
			],
		},
		schema: {
			type: 'select',
			sort: true,

			helperText: 'Select the type of resource',
			options: [
				{ label: 'Website', value: 'website' },
				{ label: 'Artice', value: 'artice' },
				{ label: 'Documentation', value: 'documentation' },
				{ label: 'Inspiration', value: 'inspiration' },
				{ label: 'Resource', value: 'resource' },
				{ label: 'Tutorial', value: 'tutorial' },
				{ label: 'Video', value: 'video' },
				{ label: 'Git Repo', value: 'git-repo' },
				{ label: 'Internal Doc', value: 'internal-doc' },
				{ label: 'Mockup', value: 'mockup' },
				{ label: 'Audio', value: 'audio' },
				{ label: 'Podcast', value: 'podcast' },
				{ label: 'Blog', value: 'blog' },
				{ label: 'Book', value: 'book' },
				{ label: 'Other', value: 'other' },
			],
		},
	},
	attachment: {
		title: 'Attachment',
		type: 'string',
		edit: true,
		schema: { type: 'file' },
	},
	note: {
		title: 'Note',
		type: 'string',
		edit: true,
		schema: {
			type: 'textarea',
		},
	},
	tags: {
		title: 'Tags',
		type: 'array-string',
		edit: true,
		schema: {
			type: 'tag',
		},
	},
	priority: {
		title: 'Priority',
		type: 'string',
		sort: true,
		edit: true,
		filter: {
			name: 'priority',
			field: 'priority_in',
			type: 'multi-select',
			label: 'Priority',
			title: 'Filter by Priority',
			options: [
				{ label: 'Low', value: 'low' },
				{ label: 'Medium', value: 'medium' },
				{ label: 'High', value: 'high' },
				{ label: 'Highest', value: 'highest' },
			],
		},
		schema: {
			type: 'select',

			sort: true,
			helperText: 'Select the priority of the resource',
			options: [
				{ label: 'Low', value: 'low' },
				{ label: 'Medium', value: 'medium' },
				{ label: 'High', value: 'high' },
				{ label: 'Highest', value: 'highest' },
			],
		},
	},
	status: {
		title: 'Status',
		type: 'string',
		sort: true,
		edit: true,
		filter: {
			name: 'status',
			field: 'status_in',
			type: 'multi-select',
			label: 'Status',
			title: 'Filter by Status',
			options: [
				{ label: 'Active', value: 'active' },
				{ label: 'Archived', value: 'archived' },
				{ label: 'Depricated', value: 'depricated' },
			],
		},
		schema: {
			type: 'select',
			sort: true,
			helperText: 'Select the status of the resource',
			tooltip: 'Status of the resource',
			options: [
				{ label: 'Active', value: 'active' },
				{ label: 'Archived', value: 'archived' },
				{ label: 'Depricated', value: 'depricated' },
			],
		},
	},
	isRecommended: {
		title: 'Is recommended',
		type: 'boolean',
		sort: true,
		edit: true,
		filter: {
			name: 'isRecommended',
			type: 'boolean',
			label: 'Is recommended',
			title: 'Is the resource recommended?',
		},
		schema: {
			sort: true,
		},
	},
	focus: {
		title: 'Focus',
		type: 'string',
		sort: true,
		search: true,
		edit: true,
		filter: {
			name: 'focus',
			field: 'focus_in',
			type: 'multi-select',
			label: 'Focus',
			title: 'Filter by Focus Area',
			category: 'distinct',
			key: 'focus',
		},
		schema: {
			sort: true,
			tooltip: 'Focus area of the resource',
			helperText: 'Select the focus area of the resource eg. ui, ux, frontend, backend, etc.',
		},
	},
	createdAt: {
		title: 'Created at',
		type: 'date',
		sort: true,
		edit: true,
		filter: { name: 'createdAt', type: 'date', label: 'Created at', title: 'Filter by Created at' },
		schema: { type: 'date', tableType: 'date-only' },
	},
};
export default settings;
