// Builds the flag and map images stored on each Country (docs/widgets W-02).
//
//   node scripts/countries/buildCountryAssets.mjs <ne_50m_admin_0_countries.geojson> BD IN PK …
//
// Writes library/data/countryAssets.ts: { [code]: { flagSvg, mapSvg } }, merged
// with what's there, so countries can be added a few at a time.
//
// Sources (both free to reuse):
// - flags: flag-icons (MIT, https://github.com/lipis/flag-icons) via flagcdn.com;
// - maps: Natural Earth admin-0 countries (public domain,
//   https://www.naturalearthdata.com), drawn here as one outline per country.
//   Use the 1:50m file (ne_50m_admin_0_countries.geojson); for city states and
//   small islands (Singapore) run again with the 1:10m file for those codes.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const [geojsonPath, ...codes] = process.argv.slice(2);
if (!geojsonPath || !codes.length) {
	console.error('Usage: node scripts/countries/buildCountryAssets.mjs <geojson> BD IN …');
	process.exit(1);
}
const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../../library/data/countryAssets.ts');

const SIZE = 200;
const PAD = 8;
const FILL = '#64748B';

/** Signed area of a projected ring (shoelace). */
const area = ring => {
	let a = 0;
	for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) a += (ring[j][0] + ring[i][0]) * (ring[j][1] - ring[i][1]);
	return Math.abs(a / 2);
};

/** One country's outline as a 200×200 SVG: equirectangular, scaled by the cosine of its middle latitude. */
const mapSvg = geometry => {
	let polygons = geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates;
	// Across the antimeridian (the Aleutians), bring the far side round.
	const lons = polygons.flat(2).map(p => p[0]);
	if (Math.max(...lons) - Math.min(...lons) > 180) polygons = polygons.map(p => p.map(r => r.map(([x, y]) => [x > 0 ? x - 360 : x, y])));
	const lats = polygons.flat(2).map(p => p[1]);
	const k = Math.cos((((Math.max(...lats) + Math.min(...lats)) / 2) * Math.PI) / 180);
	let shapes = polygons.map(p => p.map(r => r.map(([x, y]) => [x * k, -y])));
	// Specks next to the main land only blur a 200-pixel picture.
	const biggest = Math.max(...shapes.map(p => area(p[0])));
	shapes = shapes.filter(p => area(p[0]) >= biggest * 0.001);
	const pts = shapes.flat(2);
	const [minX, maxX, minY, maxY] = [Math.min(...pts.map(p => p[0])), Math.max(...pts.map(p => p[0])), Math.min(...pts.map(p => p[1])), Math.max(...pts.map(p => p[1]))];
	const scale = (SIZE - 2 * PAD) / Math.max(maxX - minX, maxY - minY);
	const offX = PAD + (SIZE - 2 * PAD - (maxX - minX) * scale) / 2;
	const offY = PAD + (SIZE - 2 * PAD - (maxY - minY) * scale) / 2;
	const r1 = n => Math.round(n * 10) / 10;
	const d = shapes
		.flatMap(p => p)
		.map(ring => {
			const out = [];
			for (const [x, y] of ring) {
				const q = [r1(offX + (x - minX) * scale), r1(offY + (y - minY) * scale)];
				const last = out[out.length - 1];
				if (!last || Math.hypot(q[0] - last[0], q[1] - last[1]) >= 0.6) out.push(q);
			}
			return out.length > 2 ? `M${out.map(q => q.join(' ')).join('L')}Z` : '';
		})
		.join('');
	return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}"><path fill="${FILL}" fill-rule="evenodd" d="${d}"/></svg>`;
};

const geo = JSON.parse(fs.readFileSync(geojsonPath, 'utf8'));
let existing = {};
if (fs.existsSync(OUT)) {
	const m = fs.readFileSync(OUT, 'utf8').match(/= (\{[\s\S]*\});\s*$/);
	if (m) existing = JSON.parse(m[1]);
}

for (const raw of codes) {
	const code = raw.toUpperCase();
	const feature = geo.features.find(f => f.properties.ISO_A2_EH === code || f.properties.ISO_A2 === code);
	if (!feature) {
		console.error(`${code}: not in the map data — skipped`);
		continue;
	}
	const res = await fetch(`https://flagcdn.com/${code.toLowerCase()}.svg`);
	if (!res.ok) {
		console.error(`${code}: flag download failed (${res.status}) — skipped`);
		continue;
	}
	const flagSvg = (await res.text()).trim();
	existing[code] = { flagSvg, mapSvg: mapSvg(feature.geometry) };
	console.log(`${code}: flag ${flagSvg.length} B, map ${existing[code].mapSvg.length} B`);
}

const sorted = Object.fromEntries(Object.keys(existing).sort().map(k => [k, existing[k]]));
fs.writeFileSync(
	OUT,
	`// Generated by scripts/countries/buildCountryAssets.mjs — don't edit by hand.\n// Flags: flag-icons (MIT). Maps: Natural Earth (public domain).\nexport const COUNTRY_ASSETS: Record<string, { flagSvg: string; mapSvg: string }> = ${JSON.stringify(sorted, null, '\t')};\n`
);
console.log(`Wrote ${Object.keys(sorted).length} countries to ${path.relative(process.cwd(), OUT)}`);
