import { Admin, SettingsType, Software } from '../../imports.js';

const settings: SettingsType<any> = {
	code: {
		title: 'Code',
		type: 'string',
		search: true,
		schema: {
			default: true,
			sort: true,
		},
	},
	name: {
		title: 'Title',
		type: 'string',
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {
			default: true,
			sort: true,
		},
	},
	description: {
		title: 'Description',
		type: 'string',
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	status: {
		title: 'Status',
		type: 'string',
		sort: true,
		edit: true,
		filter: {
			name: 'status',
			field: 'status_in',
			type: 'multi-select',
			label: 'Status',
			title: 'Filter by Status',
			options: [
				{ label: 'Open', value: 'open' },
				{ label: 'In Progress', value: 'in-progress' },
				{ label: 'On Hold', value: 'on-hold' },
				{ label: 'Testing', value: 'testing' },
				{ label: 'Resolved', value: 'resolved' },
				{ label: 'Closed', value: 'closed' },
				{ label: 'Pending', value: 'pending' },
				{ label: 'Review', value: 'review' },
				{ label: 'Reopened', value: 'reopened' },
				{ label: 'Invalid', value: 'invalid' },
				{ label: 'Needs Discussion', value: 'needs-discussion' },
			],
		},
		schema: {
			type: 'select',
			sort: true,
			default: true,
			options: [
				{ label: 'Open', value: 'open' },
				{ label: 'In Progress', value: 'in-progress' },
				{ label: 'On Hold', value: 'on-hold' },
				{ label: 'Testing', value: 'testing' },
				{ label: 'Resolved', value: 'resolved' },
				{ label: 'Closed', value: 'closed' },
				{ label: 'Pending', value: 'pending' },
				{ label: 'Review', value: 'review' },
				{ label: 'Reopened', value: 'reopened' },
				{ label: 'Invalid', value: 'invalid' },
				{ label: 'Needs Discussion', value: 'needs-discussion' },
			],
		},
	},
	images: {
		title: 'Images',
		type: 'array-string',
		edit: true,
		schema: {
			type: 'image-array',
		},
	},
	attachment: {
		title: 'Attachment',
		type: 'string',
		edit: true,
		schema: {
			type: 'file',
		},
	},
	priority: {
		title: 'Priority',
		type: 'string',
		sort: true,
		edit: true,
		required: true,
		filter: {
			name: 'priority',
			field: 'priority_in',
			type: 'multi-select',
			label: 'Priority',
			title: 'Filter by Priority',
			options: [
				{ label: 'Low', value: 'low' },
				{ label: 'Medium', value: 'medium' },
				{ label: 'High', value: 'high' },
				{ label: 'Critical', value: 'critical' },
			],
		},
		schema: {
			type: 'select',
			default: true,
			sort: true,
			options: [
				{ label: 'Low', value: 'low' },
				{ label: 'Medium', value: 'medium' },
				{ label: 'High', value: 'high' },
				{ label: 'Critical', value: 'critical' },
			],
		},
	},
	type: {
		title: 'Type',
		type: 'string',
		sort: true,
		edit: true,
		required: true,
		filter: {
			name: 'type',
			field: 'type_in',
			type: 'multi-select',
			label: 'Type',
			title: 'Filter by Type',
			options: [
				{ label: 'Bug', value: 'bug' },
				{ label: 'Feature Request', value: 'feature-request' },
				{ label: 'Improvement', value: 'improvement' },
				{ label: 'Task', value: 'task' },
				{ label: 'Research', value: 'research' },
				{ label: 'Duplicate', value: 'duplicate' },
			],
		},
		schema: {
			type: 'select',
			sort: true,
			default: true,
			options: [
				{ label: 'Bug', value: 'bug' },
				{ label: 'Feature Request', value: 'feature-request' },
				{ label: 'Improvement', value: 'improvement' },
				{ label: 'Task', value: 'task' },
				{ label: 'Research', value: 'research' },
				{ label: 'Duplicate', value: 'duplicate' },
			],
		},
	},
	project: {
		title: 'Project',
		type: 'string',
		sort: true,
		edit: true,

		populate: { path: 'project', select: 'name' },
		filter: {
			name: 'project',
			field: 'project_in',
			type: 'multi-select',
			category: 'model',
			model: Software,
			key: 'name',
			label: 'Project',
			title: 'Filter by Project',
		},
		schema: {
			sort: true,
			default: true,
			type: 'data-menu',
			tableType: 'string',
			tableKey: 'project.name',
			model: 'projects',
		},
	},
	assignedTo: {
		title: 'Assigned to',
		type: 'string',
		sort: true,
		edit: true,
		populate: { path: 'assignedTo', select: 'name' },
		filter: {
			name: 'assignedTo',
			field: 'assignedTo_in',
			type: 'multi-select',
			category: 'model',
			model: Admin,
			key: 'name',
			label: 'Assigned to',
			title: 'Filter by Assigned to',
		},
		schema: {
			sort: true,
			type: 'data-menu',
			tableType: 'string',
			tableKey: 'assignedTo.name',
			model: 'admins',
		},
	},
	assignees: {
		title: 'Other Assignees/Watchers',
		type: 'array',
		edit: true,
		schema: {
			sort: true,
			type: 'data-tag',
			model: 'admins',
		},
	},
	addedBy: {
		title: 'Added by',
		type: 'string',
		sort: true,
		edit: true,

		populate: { path: 'addedBy', select: 'name' },
		filter: {
			name: 'addedBy',
			field: 'addedBy_in',
			type: 'multi-select',
			category: 'model',
			model: Admin,
			key: 'name',
			label: 'Added by',
			title: 'Filter by Added by',
		},
		schema: {
			sort: true,
			type: 'data-menu',
			tableType: 'string',
			tableKey: 'addedBy.name',
			model: 'admins',
		},
	},
	note: {
		title: 'Note',
		type: 'string',
		search: true,
		edit: true,
		schema: { type: 'textarea' },
	},
	dueDate: {
		title: 'Due date',
		type: 'date',
		sort: true,
		edit: true,
		filter: { name: 'dueDate', type: 'date', label: 'Due date', title: 'Filter by Due date' },
		schema: { type: 'date', tableType: 'date-only', default: true },
	},
	isActive: {
		title: 'Is active',
		type: 'boolean',
		sort: true,
		edit: true,
		filter: { name: 'isActive', type: 'boolean', label: 'Is active', title: 'Filter by Is active' },
		schema: { sort: true },
	},
	createdAt: {
		title: 'Created at',
		type: 'date',
		sort: true,

		filter: { name: 'createdAt', type: 'date', label: 'Created at', title: 'Filter by Created at' },
		schema: { type: 'date', tableType: 'string', sort: true },
	},
};

export default settings;
