import { PlannedModel, PlannedProject, SettingsType } from '../../../imports.js';

const settings: SettingsType<any> = {
	name: {
		title: 'Name',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {
			sort: true,
			default: true,
		},
	},
	model: {
		title: 'Model',
		type: 'string',
		sort: true,
		search: false,
		edit: true,
		populate: { path: 'model', select: 'name' },
		filter: {
			name: 'model',
			field: 'model_in',
			type: 'multi-select',
			category: 'model',
			model: PlannedModel,
			key: 'name',
			label: 'Model',
			title: 'Filter by Model',
		},
		schema: {
			type: 'data-menu',
			tableType: 'string',
			tableKey: 'model.name',
			model: 'plannedmodels',
			sort: true,
		},
	},
	project: {
		title: 'Project',
		type: 'string',
		sort: true,
		search: false,
		edit: true,
		populate: { path: 'project', select: 'name' },
		filter: {
			name: 'project',
			field: 'project_in',
			type: 'multi-select',
			category: 'model',
			model: PlannedProject,
			key: 'name',
			label: 'Project',
			title: 'Filter by Project',
		},
		schema: {
			type: 'data-menu',
			tableType: 'string',
			tableKey: 'project.name',
			model: 'plannedprojects',
			sort: true,
		},
	},
	description: {
		title: 'Description',
		type: 'string',
		sort: false,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
			default: true,
		},
	},
	type: {
		title: 'Type',
		type: 'string',
		sort: true,
		edit: true,
		filter: {
			name: 'type',
			field: 'type_in',
			type: 'multi-select',
			label: 'Type',
			title: 'Filter by Type',
			options: [
				{ label: 'String', value: 'String' },
				{ label: 'Number', value: 'Number' },
				{ label: 'Date', value: 'Date' },
				{ label: 'Boolean', value: 'Boolean' },
				{ label: 'ObjectId', value: 'ObjectId' },
				{ label: 'Array', value: 'Array' },
				{ label: 'Object', value: 'Object' },
			],
		},
		schema: {
			sort: true,
			default: true,
			type: 'select',
			options: [
				{ label: 'String', value: 'String' },
				{ label: 'Number', value: 'Number' },
				{ label: 'Date', value: 'Date' },
				{ label: 'Boolean', value: 'Boolean' },
				{ label: 'Object id', value: 'ObjectId' },
				{ label: 'Array', value: 'Array' },
				{ label: 'Object', value: 'Object' },
			],
		},
	},
	required: {
		title: 'Required',
		type: 'boolean',
		sort: true,
		edit: true,
		filter: { name: 'required', type: 'boolean', label: 'Required', title: 'Is Required' },
		schema: {
			default: true,
			sort: true,
		},
	},
	default: {
		title: 'Default',
		type: 'string',
		edit: true,
		schema: {
			default: true,
			sort: true,
		},
	},
	ref: {
		title: 'Ref',
		type: 'string',
		search: true,
		edit: true,
		trim: true,
		schema: {
			sort: true,
			default: true,
		},
	},
	enum: {
		title: 'Enum',
		type: 'array-string',
		search: false,
		edit: true,
		schema: {
			type: 'tag',
		},
	},
	trim: {
		title: 'Trim',
		type: 'boolean',
		search: false,
		edit: true,
		schema: {},
	},
	lowercase: {
		title: 'Lowercase',
		type: 'boolean',
		edit: true,
		schema: {},
	},
	unique: {
		title: 'Unique',
		type: 'boolean',
		edit: true,
		schema: {},
	},
	match: {
		title: 'Match',
		type: 'string',
		edit: true,
		trim: true,
		schema: {
			helperText: 'Regular expression',
		},
	},
	isImmutable: {
		title: 'Is immutable',
		type: 'boolean',
		sort: true,
		edit: true,
		filter: {
			name: 'isImmutable',
			type: 'boolean',
			label: 'Is immutable',
			title: 'Filter by Is immutable',
		},
		schema: {
			sort: true,
			helperText: 'Immutable fields cannot be updated',
		},
	},
	note: {
		title: 'Note',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	createdAt: {
		title: 'Created at',
		type: 'date',
		sort: true,
		edit: true,
		schema: { type: 'date', tableType: 'date-only', sort: true },
	},
};

export default settings;
