import { Types } from 'mongoose';

type ShopType = {
	id: string;
	name: string;
	description: string;
	shippingCharge: number;
	template?: number;
	logo?: string;
	image?: string;
	coverImage?: string;
	location?: string;
	address?: string;
	email: string;
	expire: Date;
	deployment?: Types.ObjectId;
	trial: boolean;
	url?: string;
	phone: string;
	package?: any;
	isDeleted?: boolean;
	isActive: boolean;
	createdAt: Date;
	owner: Types.ObjectId;
	faq: { title: string; description: string }[];
	terms: string[];
	smsBalance: number;
	smsExpense: number;
	website?: string;
	instagram?: string;
	facebook?: string;
	linkedin?: string;
	twitter?: string;
	whatsapp?: string;
	telegram?: string;
	daraz?: string;
	youtube?: string;
	tiktok?: string;
};

export default ShopType;
