import { SettingsType } from '../../imports';

const settings: SettingsType<any> = {
	coverImage: {
		title: 'Page Cover Image',
		type: 'uri',
		edit: true,
		schema: {
			type: 'image',
		},
	},
	title: {
		title: 'Hero Title',
		type: 'string',
		edit: true,
		schema: {},
	},
	subtitle: {
		title: 'Hero Subtitle',
		type: 'string',
		edit: true,
		schema: {
			type: 'textarea',
		},
	},
	description: {
		title: 'Description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		schema: {
			type: 'textarea',
		},
	},
	icon: {
		title: 'Icon',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		schema: {
			type: 'image',
		},
	},
	name: {
		title: 'Name',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {
			default: true,
			sort: true,
		},
	},
	shortDescription: {
		title: 'Short description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {
			type: 'textarea',
			default: true,
		},
	},
	status: {
		title: 'Status',
		type: 'string',
		sort: true,
		search: true,
		edit: true,
		required: true,
		filter: {
			name: 'status',
			field: 'status_in',
			type: 'multi-select',
			label: 'Status',
			title: 'Filter by Status',
			options: [
				{
					label: 'Draft',
					value: 'draft',
				},
				{
					label: 'Published',
					value: 'published',
				},
				{
					label: 'Archived',
					value: 'archived',
				},
			],
		},
		schema: {
			default: true,
			sort: true,
			type: 'select',
			options: [
				{
					label: 'Draft',
					value: 'draft',
				},
				{
					label: 'Published',
					value: 'published',
				},
				{
					label: 'Archived',
					value: 'archived',
				},
			],
		},
	},
	toStaticPage: {
		title: 'To Static Page',
		type: 'boolean',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'toStaticPage',
			type: 'boolean',
			label: 'To static page',
			title: 'Filter by To static page',
		},
		schema: {
			helperText: 'If checked, this redirect will be to a static page',
		},
	},
	staticPageUrl: {
		title: 'Static page url',
		type: 'string',
		edit: true,
		schema: {
			helperText: 'If to static page is true, this redirect will be to this static page uri',
		},
	},
	isFeatured: {
		title: 'Is featured',
		type: 'boolean',
		sort: true,
		edit: true,

		filter: {
			name: 'isFeatured',
			type: 'boolean',
			label: 'Is featured',
			title: 'Filter by Is featured',
		},
		schema: {
			default: true,
			sort: true,
		},
	},
	priority: {
		title: 'Priority',
		type: 'number',
		edit: true,
		required: true,
		schema: {
			default: true,
			sort: true,
		},
	},
	businessNeedsTitle: {
		title: 'Business needs title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	businessNeedsDescription: {
		title: 'Business needs description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	whyDigitalTitle: {
		title: 'Why digital title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	whyDigitalDescription: {
		title: 'Why digital description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	offersTitle: {
		title: 'Offers title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	offersDescription: {
		title: 'Offers description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	offers: {
		title: 'Offers',
		type: 'array',
		sort: false,
		search: false,
		edit: true,
		schema: {
			type: 'data-tag',
			model: 'offers',
		},
	},
	featureTitle: {
		title: 'Feature title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	featureDescription: {
		title: 'Feature description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	features: {
		title: 'Features',
		type: 'array',
		sort: false,
		search: false,
		edit: true,
		schema: {
			type: 'data-tag',
			model: 'features',
		},
	},
	benifitTitle: {
		title: 'Benifit title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	benifitDescription: {
		title: 'Benifit description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	benifits: {
		title: 'Benifits',
		type: 'array',
		sort: false,
		search: false,
		edit: true,
		schema: {
			type: 'data-tag',
			model: 'features',
		},
	},
	ctaTitle: {
		title: 'Cta title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	ctaDescription: {
		title: 'Cta description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	ctaButtonText: {
		title: 'Cta button text',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	ctaButtonLink: {
		title: 'Cta button link',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	metaImage: {
		title: 'Meta image',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'image',
		},
	},
	metaTitle: {
		title: 'Meta title',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {},
	},
	metaDescription: {
		title: 'Meta description',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'textarea',
		},
	},
	metaSlug: {
		title: 'Meta slug',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		trim: true,
		schema: {
			type: 'slug',
		},
	},
	createdAt: {
		title: 'Created at',
		type: 'date',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'createdAt',
			type: 'date',
			label: 'Created at',
			title: 'Filter by Created at',
		},
		schema: {
			type: 'date',
			tableType: 'string',
		},
	},
};

export default settings;
